### ISSUE TITLE
notebooks don't work until you save the file

### ISSUE THREAD

**Issue by mtoy-googly-moogly** [malloydata/malloy-vscode-extension#121]
![Screenshot 2023-04-25 at 8 16 35 AM](https://user-images.githubusercontent.com/66150587/234326599-e62e83e6-9555-4c0c-8055-899b5c9d506b.png)

Once I save this to a file, the error goes away.

**Comment by whscullin** [comment]
I know what this is, and I thought I had fixed it, but apparently I did not.

**Comment by whscullin** [comment]
Fixed by https://github.com/malloydata/malloy-vscode-extension/pull/124 - Unsaved documents do not have a working directory, so the code for attempting to determine the working directory was blowing up. 

A side effect WRT to duckdb connections is that if you have an unsaved document, it is unlikely that it will find any parquet or csv files, because of this nether-world that VS Code puts it where I cannot determine a working directory.
